---
title: "dissertation"
author: '1'
date: "2022/7/31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Descriptive and data preperation

```{r}
library(survival)
library(devtools)
library(mombf)
library(forecast)
library(compareGroups)
library(forcats)
library(glmnet)
library(ggplot2)
library(dplyr)
library(randomForestSRC)

## Import flchain data set
data(flchain)
head(flchain)
hist(flchain$age)
table(flchain$sample.yr)
data<-flchain

## Recoding diagnose of MGUS
data$mgus[data$mgus == "1"] <- "Yes"
data$mgus[data$mgus == "0"] <- "No"
data$mgus <- factor(data$mgus)

## Recoding vital status
data$death[data$death == "1"] <- "Dead"
data$death[data$death == "0"] <- "Alive"
data$death <- factor(data$death)

## Recoding sample year
data$sample.yr[data$sample.yr == "1995"] <- "Early"
data$sample.yr[data$sample.yr == "1996"] <- "Early"
data$sample.yr[data$sample.yr == "1997"] <- "Early"
data$sample.yr[data$sample.yr == "1998"] <- "Mid"
data$sample.yr[data$sample.yr == "1999"] <- "Mid"
data$sample.yr[data$sample.yr == "2000"] <- "Mid"
data$sample.yr[data$sample.yr == "2001"] <- "Late"
data$sample.yr[data$sample.yr == "2002"] <- "Late"
data$sample.yr[data$sample.yr == "2003"] <- "Late"
data$sample.yr <- factor(data$sample.yr)
```


```{r}
## Descriptive statistics
Table <- compareGroups(death ~ age + sex + sample.yr + kappa + lambda + flc.grp + creatinine + mgus, data = data)
TableOne <- createTable(Table, show.all = TRUE, show.p.overall = FALSE)
TableOne

Table_One <- strataTable(TableOne, "sample.yr")
Table_One
export2latex(Table_One, file='Table1.tex')

```

## Early samples

```{r}
# Complete cases of the variables of interest
data.c <- data[,c(1,2,3,4,5,7,8,9,10)]
mean(complete.cases(data.c)) # completeness proportion, all missing values are creatinine
data.c <- data.c[complete.cases(data.c),]

# Extracting early samples
data.c <- data.c[which(data.c$sample.yr=="Early"),]

# Survival times
# Assigning half-day survival to the zero-survivors
data.c$futime <- ifelse(data.c$futime==0,0.5,data.c$futime)

# Histogram of survival time
pdf("Graph1.pdf")
hist(data.c$futime, breaks = 50, xlab = "Survival time (day)", probability = TRUE, main = "Early sample")
box()
dev.off()

data.c$death<-as.numeric(data.c$death)-1
y= Surv(log(data.c$futime/365.25), event=data.c$death)
data.c$kappa <- scale(data.c$kappa) # scaled kappa
data.c$creatinine <- scale(data.c$creatinine) # scaled creatinine 
data.c$sex <- as.numeric(data.c$sex)-1 # sex 0-1
data.c$mgus<-as.numeric(data.c$mgus)-1

# Design matrix
X= as.matrix(data.c[,-c(3,8,9)]);  

set.seed(2022)

# Bayesian Variable Selection
# Priors
priorCoefz = zellnerprior(taustd=1) # g-prior
priorCoefm= momprior(taustd=1) # p-mom
priorGroup= groupzellnerprior(taustd=1)

# LINEAR EFFECTS
f= formula(paste('y ~ ',paste('X[,',1:ncol(X),']',sep='',collapse="+"),sep=''))
mslinz <- modelSelection(f, priorCoef= priorCoefz, priorDelta= modelbbprior(1,1), priorGroup=priorGroup, 
                         enumerate=TRUE)
mslinm <- modelSelection(f, priorCoef= priorCoefm, priorDelta= modelbbprior(1,1), priorGroup=priorGroup, 
                         enumerate=TRUE)

new.names <- c("Intercept",colnames(X))

#MARGINAL POSTERIOR INCLUSION PROB FOR Zellner's prior
margpp.aftz = mslinz$margpp
names(margpp.aftz) <- new.names
margpp.aftz
#POSTERIOR Model PROB FOR Zellner's prior
pp.aftz= postProb(mslinz)
head(pp.aftz)

#MARGINAL POSTERIOR INCLUSION PROB FOR AFT-pMOMZ 
margpp.aftmom = mslinm$margpp
names(margpp.aftmom) <- new.names
margpp.aftmom
#POSTERIOR Model PROB FOR AFT-pMOMZ 
pp.aftmom= postProb(mslinm)
head(pp.aftmom)

# Order variables by inclusion probability
new.names[order(margpp.aftmom, decreasing = TRUE)]
new.names[order(margpp.aftz, decreasing = TRUE)]
cbind(margpp.aftz,margpp.aftmom)

# Plot of PIP--zellner
margpp.aftz <- margpp.aftz[-which(names(margpp.aftz) == "Intercept")]
data_plot <- order(margpp.aftz, decreasing = FALSE)
data_plot_names <- names(margpp.aftz)[order(margpp.aftz, decreasing = FALSE)]

Bay_z_early_main<-data.frame(y = margpp.aftz[data_plot],
           x = factor(data_plot_names,
                      data_plot_names,
                      ordered = T)) %>% 
  ggplot(aes(x = x, y = y, label = format(y, digits = 1))) + 
  geom_bar(col = "#000000", fill = "#a3a3a3", stat="identity") +
  geom_text(nudge_y = 0.02) + 
  xlab("") +
  scale_y_continuous(name = "Posterior inclusion probability AFT-Zellner(complete,early)",
                     expand = c(0, 0), limits = c(0, 1.07), breaks = c(0:10)/10) + 
  coord_flip() +
  theme_classic() + 
  theme(axis.text = element_text(size = 10, color = "black"),
        axis.title.x = element_text(size = 13, vjust = 0.1))
pdf("Graph4.pdf")
print(Bay_z_early_main)
dev.off()

# Plot of PIP--pmom
margpp.aftmom <- margpp.aftmom[-which(names(margpp.aftmom) == "Intercept")]
data_plot <- order(margpp.aftmom, decreasing = FALSE)
data_plot_names <- names(margpp.aftmom)[order(margpp.aftmom, decreasing = FALSE)]

Bay_mom_early_main<-data.frame(y = margpp.aftmom[data_plot],
           x = factor(data_plot_names,
                      data_plot_names,
                      ordered = T)) %>% 
  ggplot(aes(x = x, y = y, label = format(y, digits = 1))) + 
  geom_bar(col = "#000000", fill = "#a3a3a3", stat="identity") +
  geom_text(nudge_y = 0.02) + 
  xlab("") +
  scale_y_continuous(name = "Posterior inclusion probability AFT-pMoM(complete,early)",
                     expand = c(0, 0), limits = c(0, 1.07), breaks = c(0:10)/10) + 
  coord_flip() +
  theme_classic() + 
  theme(axis.text = element_text(size = 10, color = "black"),
        axis.title.x = element_text(size = 13, vjust = 0.1))
pdf("Graph5.pdf")
print(Bay_mom_early_main)
dev.off()

# Cox-LASSO 
# Survival object with times
y2 <- Surv(time = data.c$futime/365.25, event=data.c$death)
X2 <- X

cv.fit= try(cv.glmnet(x =  X2, y = y2, family="cox", 
                      maxit=10000, nfolds=10, alpha=1), silent=FALSE)
fit= try(glmnet(x = X2, y=y2, family = "cox", maxit=10000, alpha=1), silent=TRUE)
# active variables (lambda.min)
b.coxlasso = as.double(coef(fit, s=cv.fit$lambda.min))
new.names[-1][which(b.coxlasso!=0)]
# active variables (lambda.1se)
b2.coxlasso = as.double(coef(fit, s=cv.fit$lambda.1se))
new.names[-1][which(b2.coxlasso!=0)]

# Compare the variable importance by the magnitude of its coefficients (more distant from zero, greater the importance).
# ggplot of variable importance (lambda.min)
data_plot <- order(b.coxlasso, decreasing = FALSE)
data_plot_names <- colnames(X)[order(b.coxlasso, decreasing = FALSE)]

lasso_min_early_main<-data.frame(y = b.coxlasso[data_plot],
           x = factor(data_plot_names,
                      data_plot_names,
                      ordered = T)) %>% 
  ggplot(aes(x = x, y = y, label = format(y, digits = 1))) + 
  geom_bar(col = "#000000", fill = "#a3a3a3", stat="identity") +
  geom_text(nudge_y = 0.02) + 
  xlab("") +
  scale_y_continuous(name = "Variable Importance CoxLasso-lambda.min(complete,early)",
                     expand = c(0, 0), limits = c(0, 0.3), breaks = c(0:10)/10) + 
  coord_flip() +
  theme_classic() + 
  theme(axis.text = element_text(size = 10, color = "black"),
        axis.title.x = element_text(size = 13, vjust = 0.1))
pdf("Graph8.pdf")
print(lasso_min_early_main)
dev.off()

# ggplot of variable importance (lambda.1se)
data_plot <- order(b2.coxlasso, decreasing = FALSE)
data_plot_names <- colnames(X)[order(b2.coxlasso, decreasing = FALSE)]

lasso_1se_early_main<-data.frame(y = b2.coxlasso[data_plot],
           x = factor(data_plot_names,
                      data_plot_names,
                      ordered = T)) %>% 
  ggplot(aes(x = x, y = y, label = format(y, digits = 1))) + 
  geom_bar(col = "#000000", fill = "#a3a3a3", stat="identity") +
  geom_text(nudge_y = 0.02) + 
  xlab("") +
  scale_y_continuous(name = "Variable Importance CoxLasso-lambda.1se(complete,early)",
                     expand = c(0, 0), limits = c(0, 0.2), breaks = c(0:10)/10) + 
  coord_flip() +
  theme_classic() + 
  theme(axis.text = element_text(size = 10, color = "black"),
        axis.title.x = element_text(size = 13, vjust = 0.1))
pdf("Graph9.pdf")
print(lasso_1se_early_main)
dev.off()


# Random survival forests
data.c$futime<-data.c$futime/365.25
data.c<-data.c[,-3]
set.seed(2022)
f.obj <- rfsrc(Surv(futime,death) ~ ., data.c, importance=TRUE)
imp<-f.obj$importance

# ggplot of variable importance
data_plot <- order(imp, decreasing = FALSE)
data_plot_names <- names(imp)[order(imp, decreasing = FALSE)]

rsf_early_main<-plot(data.frame(y = imp[data_plot],
           x = factor(data_plot_names,
                      data_plot_names,
                      ordered = T)) %>% 
  ggplot(aes(x = x, y = y, label = format(y, digits = 1))) + 
  geom_bar(col = "#000000", fill = "#a3a3a3", stat="identity") +
  geom_text(nudge_y = 0.02) + 
  xlab("") +
  scale_y_continuous(name = "Variable Importance RSF(complete)",
                     expand = c(0, 0), limits = c(-0.01, 0.5), breaks = c(0:10)/10) + 
  coord_flip() +
  theme_classic() + 
  theme(axis.text = element_text(size = 10, color = "black"),
        axis.title.x = element_text(size = 13, vjust = 0.1)))
pdf("Graph12.pdf")
print(rsf_early_main)
dev.off()

#99% asymptotic normal confidence intervals of VIMP, prediction error is C-index#
jk.obj <- subsample(f.obj)
pdf("CI_early.pdf", width = 15, height = 20)
par(oma = c(0.5, 10, 0.5, 0.5))
par(cex.axis = 2.0, cex.lab = 2.0, cex.main = 2.0, mar = c(6.0,17,1,1), mgp = c(4, 1, 0))
plot(jk.obj, xlab = "Variable Importance (x 100)", cex = 1.2)
dev.off()

```

## Mid samples pdf("VIMPsur_early_complete.pdf", width = 15, height = 20)

```{r}
# Complete cases of the variables of interest
data.c <- data[,c(1,2,3,4,5,7,8,9,10)]
data.c <- data.c[complete.cases(data.c),]

# Extracting early samples
data.c <- data.c[which(data.c$sample.yr=="Mid"),]

# Survival times
# Assiging half-day survival to the zero-survivors
data.c$futime <- ifelse(data.c$futime==0,0.5,data.c$futime)

# Histogram of survival time
pdf("Graph2.pdf")
hist(data.c$futime, breaks = 50, xlab = "Survival time (day)", probability = TRUE, main = "Mid sample")
box()
dev.off()

data.c$death<-as.numeric(data.c$death)-1
y= Surv(log(data.c$futime/365.25), event=data.c$death)
data.c$kappa <- scale(data.c$kappa) # scaled kappa
data.c$creatinine <- scale(data.c$creatinine) # scaled creatinine 
data.c$sex <- as.numeric(data.c$sex)-1 # sex 0-1
data.c$mgus<-as.numeric(data.c$mgus)-1

# Design matrix
X= as.matrix(data.c[,-c(3,8,9)]);  

set.seed(2022)
# Bayesian Variable Selection
# Priors
priorCoefz = zellnerprior(taustd=1) # g-prior
priorCoefm= momprior(taustd=1) # p-mom
priorGroup= groupzellnerprior(taustd=1)

# LINEAR EFFECTS
f= formula(paste('y ~ ',paste('X[,',1:ncol(X),']',sep='',collapse="+"),sep=''))
mslinz <- modelSelection(f, priorCoef= priorCoefz, priorDelta= modelbbprior(1,1), priorGroup=priorGroup, 
                         enumerate=TRUE)
mslinm <- modelSelection(f, priorCoef= priorCoefm, priorDelta= modelbbprior(1,1), priorGroup=priorGroup, 
                         enumerate=TRUE)

new.names <- c("Intercept",colnames(X))

#MARGINAL POSTERIOR INCLUSION PROB FOR Zellner's prior
margpp.aftz = mslinz$margpp
names(margpp.aftz) <- new.names
margpp.aftz
#POSTERIOR Model PROB FOR Zellner's prior
pp.aftz= postProb(mslinz)
head(pp.aftz)

#MARGINAL POSTERIOR INCLUSION PROB FOR AFT-pMOMZ 
margpp.aftmom = mslinm$margpp
names(margpp.aftmom) <- new.names
margpp.aftmom
#POSTERIOR Model PROB FOR AFT-pMOMZ 
pp.aftmom= postProb(mslinm)
head(pp.aftmom)

# Order variables by inclusion probability
new.names[order(margpp.aftmom, decreasing = TRUE)]
new.names[order(margpp.aftz, decreasing = TRUE)]
cbind(margpp.aftz,margpp.aftmom)

# Plot of PIP--zellner
margpp.aftz <- margpp.aftz[-which(names(margpp.aftz) == "Intercept")]
data_plot <- order(margpp.aftz, decreasing = FALSE)
data_plot_names <- names(margpp.aftz)[order(margpp.aftz, decreasing = FALSE)]

bay_z_mid_main<-data.frame(y = margpp.aftz[data_plot],
           x = factor(data_plot_names,
                      data_plot_names,
                      ordered = T)) %>% 
  ggplot(aes(x = x, y = y, label = format(y, digits = 1))) + 
  geom_bar(col = "#000000", fill = "#a3a3a3", stat="identity") +
  geom_text(nudge_y = 0.02) + 
  xlab("") +
  scale_y_continuous(name = "Posterior inclusion probability AFT-Zellner(complete,mid)",
                     expand = c(0, 0), limits = c(0, 1.07), breaks = c(0:10)/10) + 
  coord_flip() +
  theme_classic() + 
  theme(axis.text = element_text(size = 10, color = "black"),
        axis.title.x = element_text(size = 13, vjust = 0.1))
pdf("Graph14.pdf")
print(bay_z_mid_main)
dev.off()

# Plot of PIP--pmom
margpp.aftmom <- margpp.aftmom[-which(names(margpp.aftmom) == "Intercept")]
data_plot <- order(margpp.aftmom, decreasing = FALSE)
data_plot_names <- names(margpp.aftmom)[order(margpp.aftmom, decreasing = FALSE)]

bay_mom_mid_main<-data.frame(y = margpp.aftmom[data_plot],
           x = factor(data_plot_names,
                      data_plot_names,
                      ordered = T)) %>% 
  ggplot(aes(x = x, y = y, label = format(y, digits = 1))) + 
  geom_bar(col = "#000000", fill = "#a3a3a3", stat="identity") +
  geom_text(nudge_y = 0.02) + 
  xlab("") +
  scale_y_continuous(name = "Posterior inclusion probability AFT-pMoM(complete,mid)",
                     expand = c(0, 0), limits = c(0, 1.07), breaks = c(0:10)/10) + 
  coord_flip() +
  theme_classic() + 
  theme(axis.text = element_text(size = 10, color = "black"),
        axis.title.x = element_text(size = 13, vjust = 0.1))
pdf("Graph15.pdf")
print(bay_mom_mid_main)
dev.off()


# Cox-LASSO 
# Survival object with times
y2 <- Surv(time = data.c$futime/365.25, event=data.c$death)
X2 <- X

cv.fit= try(cv.glmnet(x =  X2, y = y2, family="cox", 
                      maxit=10000, nfolds=10, alpha=1), silent=FALSE)
fit= try(glmnet(x = X2, y=y2, family = "cox", maxit=10000, alpha=1), silent=TRUE)
# active variables (lambda.min)
b.coxlasso = as.double(coef(fit, s=cv.fit$lambda.min))
new.names[-1][which(b.coxlasso!=0)]
# active variables (lambda.1se)
b2.coxlasso = as.double(coef(fit, s=cv.fit$lambda.1se))
new.names[-1][which(b2.coxlasso!=0)]
# There is no direct calculation of variable importance in the glmnet. But we
#compare the variable importance by the magnitude of its coefficients.
#i.e. more distant from zero, greater the importance

# ggplot of variable importance lambda.min
data_plot <- order(b.coxlasso, decreasing = FALSE)
data_plot_names <- colnames(X)[order(b.coxlasso, decreasing = FALSE)]

lasso_min_mid_main<-data.frame(y = b.coxlasso[data_plot],
           x = factor(data_plot_names,
                      data_plot_names,
                      ordered = T)) %>% 
  ggplot(aes(x = x, y = y, label = format(y, digits = 1))) + 
  geom_bar(col = "#000000", fill = "#a3a3a3", stat="identity") +
  geom_text(nudge_y = 0.02) + 
  xlab("") +
  scale_y_continuous(name = "Variable Importance CoxLasso-lambda.min(complete,mid)",
                     expand = c(0, 0), limits = c(0, 0.2), breaks = c(0:10)/10) + 
  coord_flip() +
  theme_classic() + 
  theme(axis.text = element_text(size = 10, color = "black"),
        axis.title.x = element_text(size = 13, vjust = 0.1))
pdf("Graph18.pdf")
print(lasso_min_mid_main)
dev.off()

# ggplot of variable importance lambda.1se
data_plot <- order(b2.coxlasso, decreasing = FALSE)
data_plot_names <- colnames(X)[order(b2.coxlasso, decreasing = FALSE)]

lasso_1se_mid_main<-data.frame(y = b2.coxlasso[data_plot],
           x = factor(data_plot_names,
                      data_plot_names,
                      ordered = T)) %>% 
  ggplot(aes(x = x, y = y, label = format(y, digits = 1))) + 
  geom_bar(col = "#000000", fill = "#a3a3a3", stat="identity") +
  geom_text(nudge_y = 0.02) + 
  xlab("") +
  scale_y_continuous(name = "Variable Importance CoxLasso-lambda.1se(complete,mid)",
                     expand = c(0, 0), limits = c(0, 0.2), breaks = c(0:10)/10) + 
  coord_flip() +
  theme_classic() + 
  theme(axis.text = element_text(size = 10, color = "black"),
        axis.title.x = element_text(size = 13, vjust = 0.1))
pdf("Graph19.pdf")
print(lasso_1se_mid_main)
dev.off()


# Random survival forests
data.c$futime<-data.c$futime/365.25
data.c<-data.c[,-3]
set.seed(2022)
f.obj <- rfsrc(Surv(futime,death) ~ ., data.c, importance=TRUE)
imp<-f.obj$importance

# ggplot of variable importance
data_plot <- order(imp, decreasing = FALSE)
data_plot_names <- names(imp)[order(imp, decreasing = FALSE)]

rsf_mid_main<-data.frame(y = imp[data_plot],
           x = factor(data_plot_names,
                      data_plot_names,
                      ordered = T)) %>% 
  ggplot(aes(x = x, y = y, label = format(y, digits = 1))) + 
  geom_bar(col = "#000000", fill = "#a3a3a3", stat="identity") +
  geom_text(nudge_y = 0.02) + 
  xlab("") +
  scale_y_continuous(name = "Variable Importance RSF(complete,mid)",
                     expand = c(0, 0), limits = c(-0.01, 0.5), breaks = c(0:10)/10) + 
  coord_flip() +
  theme_classic() + 
  theme(axis.text = element_text(size = 10, color = "black"),
        axis.title.x = element_text(size = 13, vjust = 0.1))
pdf("Graph22.pdf")
print(rsf_mid_main)
dev.off()


#99% asymptotic normal confidence intervals of VIMP, prediction error is C-index#
jk.obj <- subsample(f.obj)
pdf("CI_mid.pdf", width = 15, height = 20)
par(oma = c(0.5, 10, 0.5, 0.5))
par(cex.axis = 2.0, cex.lab = 2.0, cex.main = 2.0, mar = c(6.0,17,1,1), mgp = c(4, 1, 0))
plot(jk.obj, xlab = "Variable Importance (x 100)", cex = 1.2)
dev.off()

```

## Late samples

```{r}
# Complete cases of the variables of interest
data.c <- data[,c(1,2,3,4,5,7,8,9,10)]
data.c <- data.c[complete.cases(data.c),]

# Extracting early samples
data.c <- data.c[which(data.c$sample.yr=="Late"),]

# Survival times
# Assiging half-day survival to the zero-survivors
data.c$futime <- ifelse(data.c$futime==0,0.5,data.c$futime)

# Histogram of survival time
pdf("Graph3.pdf")
hist(data.c$futime, breaks = 50, xlab = "Survival time (day)", probability = TRUE, main = "Late sample")
box()
dev.off()

data.c$death<-as.numeric(data.c$death)-1
y= Surv(log(data.c$futime/365.25), event=data.c$death)
data.c$kappa <- scale(data.c$kappa) # scaled kappa
data.c$creatinine <- scale(data.c$creatinine) # scaled creatinine 
data.c$sex <- as.numeric(data.c$sex)-1 # sex 0-1
data.c$mgus<-as.numeric(data.c$mgus)-1

# Design matrix
X= as.matrix(data.c[,-c(3,7,8,9)]);  #all mgus in the late samples are 0, so excluding mgus 

set.seed(2022)
# Bayesian Variable Selection
# Priors
priorCoefz = zellnerprior(taustd=1) # g-prior
priorCoefm= momprior(taustd=1) # p-mom
priorGroup= groupzellnerprior(taustd=1)

# LINEAR EFFECTS
f= formula(paste('y ~ ',paste('X[,',1:ncol(X),']',sep='',collapse="+"),sep=''))
mslinz <- modelSelection(f, priorCoef= priorCoefz, priorDelta= modelbbprior(1,1), priorGroup=priorGroup,enumerate=TRUE)
mslinm <- modelSelection(f, priorCoef= priorCoefm, priorDelta= modelbbprior(1,1), priorGroup=priorGroup,enumerate=TRUE)

new.names <- c("Intercept",colnames(X))

#MARGINAL POSTERIOR INCLUSION PROB FOR Zellner's prior
margpp.aftz = mslinz$margpp
names(margpp.aftz) <- new.names
margpp.aftz
#POSTERIOR Model PROB FOR Zellner's prior
pp.aftz= postProb(mslinz)
head(pp.aftz)

#MARGINAL POSTERIOR INCLUSION PROB FOR AFT-pMOMZ 
margpp.aftmom = mslinm$margpp
names(margpp.aftmom) <- new.names
margpp.aftmom
#POSTERIOR Model PROB FOR AFT-pMOMZ 
pp.aftmom= postProb(mslinm)
head(pp.aftmom)

# Order variables by inclusion probability
new.names[order(margpp.aftmom, decreasing = TRUE)]
new.names[order(margpp.aftz, decreasing = TRUE)]
cbind(margpp.aftz,margpp.aftmom)

# Plot of PIP--zellner
margpp.aftz <- margpp.aftz[-which(names(margpp.aftz) == "Intercept")]
data_plot <- order(margpp.aftz, decreasing = FALSE)
data_plot_names <- names(margpp.aftz)[order(margpp.aftz, decreasing = FALSE)]

bay_z_late_main<-data.frame(y = margpp.aftz[data_plot],
           x = factor(data_plot_names,
                      data_plot_names,
                      ordered = T)) %>% 
  ggplot(aes(x = x, y = y, label = format(y, digits = 1))) + 
  geom_bar(col = "#000000", fill = "#a3a3a3", stat="identity") +
  geom_text(nudge_y = 0.02) + 
  xlab("") +
  scale_y_continuous(name = "Posterior inclusion probability AFT-Zellner(complete,late)",
                     expand = c(0, 0), limits = c(0, 1.07), breaks = c(0:10)/10) + 
  coord_flip() +
  theme_classic() + 
  theme(axis.text = element_text(size = 10, color = "black"),
        axis.title.x = element_text(size = 13, vjust = 0.1))
pdf("Graph24.pdf")
print(bay_z_late_main)
dev.off()

# Plot of PIP--pmom
margpp.aftmom <- margpp.aftmom[-which(names(margpp.aftmom) == "Intercept")]
data_plot <- order(margpp.aftmom, decreasing = FALSE)
data_plot_names <- names(margpp.aftmom)[order(margpp.aftmom, decreasing = FALSE)]

bay_mom_late_main<-data.frame(y = margpp.aftmom[data_plot],
           x = factor(data_plot_names,
                      data_plot_names,
                      ordered = T)) %>% 
  ggplot(aes(x = x, y = y, label = format(y, digits = 1))) + 
  geom_bar(col = "#000000", fill = "#a3a3a3", stat="identity") +
  geom_text(nudge_y = 0.02) + 
  xlab("") +
  scale_y_continuous(name = "Posterior inclusion probability AFT-pMoM(complete,late)",
                     expand = c(0, 0), limits = c(0, 1.07), breaks = c(0:10)/10) + 
  coord_flip() +
  theme_classic() + 
  theme(axis.text = element_text(size = 10, color = "black"),
        axis.title.x = element_text(size = 13, vjust = 0.1))
pdf("Graph25.pdf")
print(bay_mom_late_main)
dev.off()

# Cox-LASSO 
# Survival object with times
y2 <- Surv(time = data.c$futime/365.25, event=data.c$death)
X2 <- as.matrix(data.c[,-c(3,8,9)])

cv.fit= try(cv.glmnet(x =  X2, y = y2, family="cox", 
                      maxit=10000, nfolds=10, alpha=1), silent=FALSE)
fit= try(glmnet(x = X2, y=y2, family = "cox", maxit=10000, alpha=1), silent=TRUE)
# active variables (lambda.min)
b.coxlasso = as.double(coef(fit, s=cv.fit$lambda.min))
new.names[-1][which(b.coxlasso!=0)]
# active variables (lambda.1se)
b2.coxlasso = as.double(coef(fit, s=cv.fit$lambda.1se))
new.names[-1][which(b2.coxlasso!=0)]
# There is no direct calculation of variable importance in the glmnet. But we
#compare the variable importance by the magnitude of its coefficients.
#i.e. more distant from zero, greater the importance

# ggplot of variable importance lambda.min
data_plot <- order(b.coxlasso, decreasing = FALSE)
data_plot_names <- colnames(X2)[order(b.coxlasso, decreasing = FALSE)]

lasso_min_late_main<-data.frame(y = b.coxlasso[data_plot],
           x = factor(data_plot_names,
                      data_plot_names,
                      ordered = T)) %>% 
  ggplot(aes(x = x, y = y, label = format(y, digits = 1))) + 
  geom_bar(col = "#000000", fill = "#a3a3a3", stat="identity") +
  geom_text(nudge_y = 0.02) + 
  xlab("") +
  scale_y_continuous(name = "Variable Importance CoxLasso-lambda.min(complete,late)",
                     expand = c(0, 0), limits = c(0, 0.2), breaks = c(0:10)/10) + 
  coord_flip() +
  theme_classic() + 
  theme(axis.text = element_text(size = 10, color = "black"),
        axis.title.x = element_text(size = 13, vjust = 0.1))
pdf("Graph28.pdf")
print(lasso_min_late_main)
dev.off()

# ggplot of variable importance lambda.1se
data_plot <- order(b2.coxlasso, decreasing = FALSE)
data_plot_names <- colnames(X2)[order(b2.coxlasso, decreasing = FALSE)]

lasso_1se_late_main<-data.frame(y = b2.coxlasso[data_plot],
           x = factor(data_plot_names,
                      data_plot_names,
                      ordered = T)) %>% 
  ggplot(aes(x = x, y = y, label = format(y, digits = 1))) + 
  geom_bar(col = "#000000", fill = "#a3a3a3", stat="identity") +
  geom_text(nudge_y = 0.02) + 
  xlab("") +
  scale_y_continuous(name = "Variable Importance CoxLasso-lambda.1se(complete,late)",
                     expand = c(0, 0), limits = c(0, 0.2), breaks = c(0:10)/10) + 
  coord_flip() +
  theme_classic() + 
  theme(axis.text = element_text(size = 10, color = "black"),
        axis.title.x = element_text(size = 13, vjust = 0.1))
pdf("Graph29.pdf")
print(lasso_1se_late_main)
dev.off()

# Random survival forests
data.c$futime<-data.c$futime/365.25
data.c<-data.c[,-3]
set.seed(2022)
f.obj <- rfsrc(Surv(futime,death) ~ ., data.c, importance=TRUE)
imp<-f.obj$importance

# ggplot of variable importance
data_plot <- order(imp, decreasing = FALSE)
data_plot_names <- names(imp)[order(imp, decreasing = FALSE)]

rsf_late_main<-data.frame(y = imp[data_plot],
           x = factor(data_plot_names,
                      data_plot_names,
                      ordered = T)) %>% 
  ggplot(aes(x = x, y = y, label = format(y, digits = 1))) + 
  geom_bar(col = "#000000", fill = "#a3a3a3", stat="identity") +
  geom_text(nudge_y = 0.02) + 
  xlab("") +
  scale_y_continuous(name = "Variable Importance RSF(complete,late)",
                     expand = c(0, 0), limits = c(-0.01, 0.6), breaks = c(0:10)/10) + 
  coord_flip() +
  theme_classic() + 
  theme(axis.text = element_text(size = 10, color = "black"),
        axis.title.x = element_text(size = 13, vjust = 0.1))
pdf("Graph32.pdf")
print(rsf_late_main)
dev.off()

#99% asymptotic normal confidence intervals of VIMP, prediction error is C-index#
jk.obj <- subsample(f.obj)
pdf("CI_late.pdf", width = 15, height = 20)
par(oma = c(0.5, 10, 0.5, 0.5))
par(cex.axis = 2.0, cex.lab = 2.0, cex.main = 2.0, mar = c(6.0,17,1,1), mgp = c(4, 1, 0))
plot(jk.obj, xlab = "Variable Importance (x 100)", cex = 1.2)
dev.off()

```

